# Generated by Django 5.2 on 2025-05-30 14:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('numContacto', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandados_publicados', to='login_registro.usuario')),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandados_aceptados', to='login_registro.usuario')),
            ],
        ),
    ]
